vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
